### PR TITLE
1783 more efficient octomap usage

### PR DESCRIPTION
**Pull request by dnrohr**

### CODE REVIEW

**Comment by dnrohr** [comment]
@brenden-square Passes regression -- ready for review

**Review by brenden-gibbons — CHANGES_REQUESTED** [review]
Nice fix for the filtering, it seems to be functioning as intended now.

I ran some tests with an SR1F sim at 1 RTF in the default sim tank (227) and am seeing an increase in octomap_server CPU usage of about 3x with these changes.  My best guess is that publishing all of the maps is expensive and it's now happening at a higher frequency.  Here's a rough overview of the test I ran on both on 501a2ddaf5f37489a8f973777ff1fce76565678e of master(utbot) with 8a3e0218b57502b02a175fb21652e73901cfa7f1 of kinetic-devel(octomap_mapping) and 8f9d97b0187e1e6a2db90446e1e4ab615167123b of 1783-more-efficient-octomap-usage(utbot) and 81d705102fb733b9c059f586b65d674d301dff5d of 1783-more-efficient-octomap-usage(octomap_mapping):

1. Started SR1F sim at 1 RTF in default tank (227)
2. Manually drove the vehicle along a straight path to position 1,-7, then fully rotated the vehicle counterclockwise twice manually at ~20deg/s. 
3. Ran the regression_test_1_ins_alignment_nav_fix_floor mission
4. Ran the regression_test_5_ndt_inspection_ics mission

On utbot master and kinetic-devel, after the first two manual spins, I observed ocotomap_server CPU usage of ~65% when the vehicle was idle and ~110% whenever it was in motion.  On 1783-more-efficient-octomap-usage and 1783-more-efficient-octomap-usage, I observed ocotomap_server CPU usage of ~16% when the vehicle was idle and ~35% whenever it was in motion.

Could you check into why octomap_server is consuming so much more CPU on this branch?

**Comment by dnrohr** [comment]
@brenden-square I changed the ISA500 sampling rate to 5Hz -- would you mind seeing if the CPU consumption looks right on your machine? After I push this branch I will change the .rosinstall commit tag to latest Square kinetic-devel

**Review by brenden-gibbons — APPROVED** [review]
I just performed a more repeatable evaluation of 1783 utbot/octomap_mapping vs master utbot with isa500 ping delay 500 and the latest kinetic-devel of octomap_mapping.  I'm seeing a small improvement to CPU usage in favor of 1783 utbot/octomap_mapping, so this LGTM

**Comment by dnrohr** [comment]
This is also running at 5Hz opposed to the previous ~3.3Hz

**Pull request merged**
